; General notes
;   This program converts a BASIC TAP file to a DCK and ROM file
;       and will optionally append files to the end of the
;       BASIC code. The files produced by the program will
;       always be a multiple of 8192 bytes and can be
;       of any size the user wishes depending only on the size
;       of the BASIC program and the total size of any appended
;       files.
;
; File names
; This program should work with both Windows and the various flavors
;	of Linux.
;	Windows users: DO NOT use embedded spaces in your file names -
;		they will likely crash the program. Windows handles file
;		names with spaces in a jankey manner so "just say no"
;		to spaces. Try camel case or underscores.
;
[TOP]
; this is a magic value the main program uses to verify this is
;   a valid control file
Sentinel = 5>Ychs+IhFd[U:q`[tDg`x>[=u=vYFFG

[TAPFILE]
; the subfile key is used to select which TAP subfile in a multiple
;   file tap file will be converted. If this value is less than one,
;   negative, or is greater than the number of subfiles in the
;   TAP file, the program defaults to the first subfile. this key can
;   be omitted if there is only one subfile in the TAP file
;
subfile = 3
; the name of the file containing the TAP file/subfile to convert.
;   relative paths can be used.
;
tapfile = "E:\myPython\tapFiles\junk.TAP"

[HDRDAT]
; ROM start address of BASIC program. This parameter can be
;	omitted or commented out and the default of $8008 will
;	be used
basStart = $8008
; Variable space for machine code variables. This parameter
;	can be omitted and the default of 0 will be used
varSpace = $0008
; Auto start override. If the BASIC program already enables
;	auto start via the SAVE 'filename' LINE xx command, this
;	flag is ignored. If there is no BASIC start line, then this
;	flag is honored. This parameter may be omitted and the
;	BASIC program will control the autostart.
autoStart = 1

; not used
machinecode = 0

[OUTFILES]
binFile = "E:\myPython\tapFiles\junkBin.bin"
dckFile = "E:\myPython\tapFiles\junkDock.dck"

[BINFILES]
; these are any binary files to be appended to the BASIC file. they can
;   be any type of file and there is no limit to the size of the final
;   ROM/DCK file. if there are no entries in this section the program
;   will silently ignore it
;
; each entry starts with a key name that is used to access the values.
;   the example uses "binFile3". The key name can be any alpha numeric
;   sequence but each key MUST be unique.
;
; the equal sign separates the key name from the key value
;
; the %8200 in the example is the address in the ROM file where the file
;   will start. addresses below $10000 (65536) will correspond to physical
;   addresses in the TS2068 address space. it is the user's responsibility
;   to ensure that the the files are at the correct address space. the
;   program will detect if a subsequent file will overwrite an previous
;   data and exit. also, any unused space between files will be filled
;   with the appropriate amount of $00 bytes. because of the zero fill,
;   the binary files must be listed in order of ascending address.
;
; the second field of the key value is the name of the file to be
;   appended. the program uses only the number of bytes in the file
;   keeping in mind the padding described above.
;
binFile1 = $8100, "E:\myPython\tapFiles\SPECEMU.TXT"
binFile3 = $8280, "E:\myPython\tapFiles\SHOTZEXR.TXT"

